services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres.pxnangovncbvfbjywnbv:omSriganesha06@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
      - GEMINI_API_KEY=AIzaSyDT9cCkLw4RdNmc73F9L0HJJMrMWtuRESM
      - RAZORPAY_KEY_ID=rzp_test_SPSadFsryQESjl
      - RAZORPAY_KEY_SECRET=bBYj7Q4dZGnRnf6CzFLZftIO
      - EMAIL_USER=avulakarthik189@gmail.com
      - EMAIL_PASS=pcjs qbdf cyvk czyc
    restart: always
